books:
  - title: "鴉は硝子のフリルで踊る"
    keywords: ["梅﨑実奈", "梅崎実奈", "鴉は硝子のフリルで踊る"]
    top_percentile: 30  # 上位30%を表示
  - title: "ピアニストは「ファンサ」の原点か"
    keywords: ["かげはら史帆", "ピアニストは「ファンサ」の原点か"]
    top_percentile: 30  # 上位30%を表示
  - title: "いのちの建築"
    keywords: ["手塚貴晴", "手塚由比", "いのちの建築"]
    top_percentile: 30  # 上位30%を表示